---
title: "Senegal Survey"
---

An initial survey was conducted among doctoral students in social sciences and environmental sciences at Cheikh Anta Diop University (UCAD) in Dakar, Senegal.

The aim of this survey is to produce original data that will ultimately enable the construction of a comparative analysis grid for doctoral contexts. This approach aims to shed light on the dynamics and inequalities between different training environments, whether they relate to North–South or South–South relations.

## A collaborative and co-constructed approach

The questionnaire used is the result of a collective effort within the GTDID, where doctoral students from various academic backgrounds worked together to develop the survey tools. This participatory approach aims to ensure that the questions are relevant and sensitive to the diverse realities of doctoral programmes.

## Participating doctoral schools

For this first phase, the survey involves two doctoral schools at UCAD:

-   Doctoral School of Water, Water Quality and Water Use (EDEQUE)

-   Doctoral School of Human and Social Studies (ETHOS)

This collaboration is a first step towards a broader comparative study, gradually incorporating other institutions and doctoral contexts.

